#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.model = 'cavity_magnet'
tm.sweeps = 200000
tm.thermalization = 10000
tm.binsize = 1000
tm.lattice = 'honeycomb'
tm.cavity = 'polarized'
tm.Lx = 2
tm.Ly = 2

tm.measure = ['mag', 'sucmag', 'sxsymag']

tm.J = 0.9
tm.U = 10*tm.J

tm.max_photons = 1
tm.omega = 0.4*tm.U
tm.g = 0.3
tm.phi = 0.3

tm.ed_compare = 1
tm.ed_num_states = 0

Ts = np.linspace(0.05,1,7)
couplings = [0]
for T in Ts:
        tm.task(T=T)

tm.write()
