#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.sweeps = 50000000
tm.thermalization = 10000
tm.binsize = 2000
tm.lattice = 'triangle_square'
tm.Lx = 3
tm.Ly = 1

tm.measure = ['chirality']
tm.chirality_op_tauy = True

tm.basis = 3

tm.J1 = 1
tm.J2 = 1
tm.J3 = 1
tm.Jn = 0.1
tm.Jnn = 0

tm.ed_compare = 1
tm.ed_num_states = 0

Ts = [0.1,0.2,0.3,0.4]

for T in Ts:
    tm.task(T=T)

tm.write()
