#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.sweeps = 800000
tm.thermalization = 50000
tm.binsize = 1000
tm.lattice = 'diamond_square'
tm.Lx = 2
tm.Ly = 1

tm.measure = ['j', 'jcorrlen', 'mag', 'sxmag', 'symag', 'sxsymag']

tm.J1 = 1
tm.J2 = 1.5
tm.J = 0.15

tm.basis = 'dimer'

tm.ed_compare = 1
tm.ed_num_states = 0

Ts = np.linspace(1,6,7)

for T in Ts:
    tm.task(T=T)

tm.write()
