#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.sweeps = 1000000
tm.thermalization = 90000
tm.binsize = 100
tm.lattice = 'shastry_sutherland'
tm.Lx = 2
tm.Ly = 1

tm.measure = ['j', 'jcorrlen', 'mag', 'sxmag', 'symag', 'sxsymag']

tm.J = 0.5
tm.JD = 1

tm.ed_compare = 1
tm.ed_num_states = 0

Ts = np.linspace(0.05,2,7)

for T in Ts:
    tm.task(T=T)

tm.write()
