#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.sweeps = 100000
tm.thermalization = 50000
tm.binsize = 2000
tm.lattice = 'triangle_square'
tm.Lx = 2
tm.Ly = 2

tm.measure = ['j', 'jcorrlen', 'mag', 'sxmag', 'symag', 'sxsymag']

tm.basis = 5

tm.J1 = 1
tm.J2 = 0.5
tm.J3 = 1
tm.Jn = 0.124
tm.Jnn = 0.35

tm.ed_compare = 1
tm.ed_num_states = 0

Ts = np.linspace(0.1,0.5,7)

for T in Ts:
    tm.task(T=T)

tm.write()
