#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.sweeps = 2000000
tm.thermalization = 50000
tm.binsize = 100
tm.lattice = 'triangle_square'
tm.Lx = 2
tm.Ly = 2

tm.J1 = 2.1023
tm.J2 = 3.36
tm.J3 = 1.1356
tm.Jn = 4.423
tm.Jnn=0

bases = [1, 2]

for basis in bases:
    tm.task(basis = basis)

tm.write()
