#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.sweeps = 2000000
tm.thermalization = 50000
tm.binsize = 100
tm.lattice = 'triangle_square'
tm.Lx = 2
tm.Ly = 2

tm.Jtri = 1
tm.Jin = 1
tm.Jup = 0.54
tm.Jdirect = 0.54
tm.Jindirect = 0.

tm.ed_compare = 1
tm.ed_num_states = 0

Ts = np.linspace(0.06,0.5,7)

for T in Ts:
    tm.task(T=T)

tm.write()
