#!/usr/bin/env python3
from loadleveller import taskmaker
import numpy as np

tm = taskmaker.TaskMaker(__file__, 'jobconfig.yml')
tm.sweeps = 100000
tm.thermalization = 50000
tm.binsize = 100
tm.lattice = 'triangle'
tm.Lx = 4
tm.Ly = 2

tm.J = 1.15

tm.ed_compare = 1
tm.ed_num_states = 0

Ts = np.linspace(0.06,6,7)

for T in Ts:
    tm.task(T=T)

tm.write()
